Only create '.stixmarx' if it does not exist
We're currently using the (cti-stix-elevator)[https://github.com/oasis-open/cti-stix-elevator] in our project, and during our CI builds, an exception is being thrown indicating that this call to create the `.stixmarx` directory is throwing a `FileExistsError`.

```
FileExistsError: [Errno 17] File exists: '/home/jenkins/.stixmarx'
```